# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  dogvacay.com:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "ZlLP1y;K^]<[,[#ZiEXROoxLZlBW6G;.IW,ARNF!svEd1Mx(6BH$T`BP;@P1dGrW"
      secure_auth_key: ".8q,+v`kVne+XeHk=dix|dNQ)0e99KaRMT`VHTy_BC`4>=0|4v3<z^tJq,hux3C4"
      logged_in_key: "#=?yFvm/qcZ#C!&6,UMVSxDc!T}${|t7A!$vTj.a7(9fmJW+PES#|NKhB6$?VtbY"
      nonce_key: "i-J`K!jLFr;9a(q!zWh)H{#&#Ak21fsa_8u6CQ$]M?EZu%y/I!gdtQMq&-NYw#A;"
      auth_salt: "c[tspcwwp***HqL/8%L3Wi;mKKREvZPUIn?4mfMLS6:jb#.*B<zT55{f=pR8<MG."
      secure_auth_salt: ">-,m{JmYLyej_*Vc[1MX<d4#5.kZxkQ-PtXlRktETJ35nVx]Hyw/{lI?&kQn9#$p"
      logged_in_salt: "qi?|xJ7WYY-N9_S=CVOCLwF=UFfYVW2C0AjVi<B4T/:E<)7xSz1}E/w<_%kPZSyZ"
      nonce_salt: "vgq;]LieSYAdF5dt2S_&kgZHd[0EP[g=skF;Bq*2.48d*,-xh$-BUaz#,T[5(%uJ"
